'use client';

import { SentimentChart } from '@/components/dashboard/sentimentChart';
import { SkeletonBar } from '@/components/dashboard/skeleton';
import { ChartLine, TrendingUp, TrendingDown, Info } from 'lucide-react';
import React, { useState } from 'react';

export default function SentimentLayout() {
  const [isSentimentChartLoading, setIsSentimentChartLoading] = useState(true);

  return (
    <div className='border'>
      {/* Sentiment Chart Section - Heading */}
      <div className='flex h-8 w-full border-zinc-300 bg-zinc-300 pl-4 pt-1 text-left font-sans font-medium text-gray-500'>
        <ChartLine className='mr-2 mt-1 h-4 w-4' /> Sentiment Analysis
      </div>
      {/* Label: Generated by AI */}
      <div className='ml-6 mt-3 flex h-6 w-1/6 items-center border-2 text-center text-xs text-gray-400'>
        <Info className='ml-2 mr-2 h-3 w-3' />
        Generated by AI
      </div>
      {/* Sentiment Chart Section - Inner */}
      <div className='mb-8 ml-6 mr-6 mt-4 flex flex-col items-center justify-start border'>
        {isSentimentChartLoading && <SkeletonBar />}
        <SentimentChart
          onLoadComplete={() => setIsSentimentChartLoading(false)}
        />
      </div>

      {/* Sentiment Chart Section - Opinions */}
      <div className='flex justify-between gap-x-6'>
        {/* Sentiment Chart Section - Opinions Bullish */}
        <div className='mb-6 ml-6 h-40 w-1/2 border-2'>
          <div className='flex h-8 w-full border-zinc-300 bg-zinc-300 pl-4 pt-1 text-left font-sans font-medium text-gray-500'>
            <TrendingUp className='mr-2 mt-1 h-4 w-4' /> Bullish
          </div>
        </div>
        {/* Sentiment Chart Section - Opinions Bearish */}
        <div className='mb-6 mr-6 h-40 w-1/2 border-2'>
          <div className='flex h-8 w-full border-zinc-300 bg-zinc-300 pl-4 pt-1 text-left font-sans font-medium text-gray-500'>
            <TrendingDown className='mr-2 mt-1 h-4 w-4' /> Bearish
          </div>
        </div>
      </div>
    </div>
  );
}
