'use client';

import { MindshareMap } from '@/components/features/dashboard/mindshareMap';
import { SkeletonBar } from '@/components/features/dashboard/skeleton';
import { ChartLine, Lightbulb, Info } from 'lucide-react';
import React, { useState } from 'react';

export default function MindshareLayout() {
  const [isMindshareMapLoading, setIsMindshareMapLoading] = useState(true);

  return (
    <div className='mt-16 border'>
      {/* Heading */}
      <div className='flex h-8 w-full border-zinc-300 bg-zinc-300 pl-4 pt-1 text-left font-sans font-medium text-gray-500'>
        <ChartLine className='mr-2 mt-1 h-4 w-4' /> Mindshare Map
      </div>
      {/* Label: Generated by AI */}
      <div className='ml-6 mt-3 flex h-6 w-1/6 items-center border-2 text-center text-xs text-gray-400'>
        <Info className='ml-2 mr-2 h-3 w-3' />
        Generated by AI
      </div>
      {/* Chart */}
      <div className='mb-8 ml-6 mr-6 mt-4 flex flex-col items-center justify-start border'>
        {isMindshareMapLoading && <SkeletonBar />}
        <MindshareMap onLoadComplete={() => setIsMindshareMapLoading(false)} />
      </div>

      {/* Opinions */}
      <div className='flex'>
        {/* Opinions Bullish */}
        <div className='mb-6 ml-6 mr-6 h-40 w-full border-2'>
          <div className='flex h-8 w-full border-zinc-300 bg-zinc-300 pl-4 pt-1 text-left font-sans font-medium text-gray-500'>
            <Lightbulb className='mr-2 mt-1 h-4 w-4' /> Opinions
          </div>
        </div>
      </div>
    </div>
  );
}
